import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Providers from "@/lib/Providers";
import Navbar from "@/components/ui/Navbar/Navbar";
import "tailwindcss/tailwind.css";
import FooterComponent from "@/components/ui/Footer/Footer";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body>
          {children}
          <FooterComponent />
        </body>
      </Providers>
    </html>
  );
}
