import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Providers from "@/lib/Providers";
import Navbar from "@/components/ui/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items = [
    { key: "1", label: "Home", href: "/" },
    { key: "2", label: "About", href: "/about-us" },
    { key: "3", label: "Contact", href: "/contact-us" },
  ];
  return (
    <html lang="en">
      <Providers>
        <body>
          <Navbar items={items} />
          {children}
        </body>
      </Providers>
    </html>
  );
}
